### ISSUE TITLE
express-serve-static-core.d.ts missing

### ISSUE THREAD

**Issue by mintern** [toddlucas/react-tsx-starter#1]
Thanks for providing this starter project!

When I ran your README instructions on the redux branch while using tsc 1.7.5, I got the following error during the `gulp` step:

```
/.../typings/express/express.d.ts(14,1): error TS6053: File '/.../typings/express-serve-static-core/express-serve-static-core.d.ts' not found
```

After running `tsd install express-serve-static-core -s`, everything built and started up correctly.

**Comment by toddlucas** [comment]
Thanks for the report!

**Comment by mintern** [comment]
You're welcome! This might be an upstream problem (`express` failing to declare a TS dependency?), but I'm not familiar enough with the Node ecosystem to know for sure. Thanks again!

**Comment by toddlucas** [comment]
It looks like express.d.ts was refactored in February, so this is now required. I hadn't updated my express TS definitions so I didn't notice it. Thanks, again.
