### ISSUE TITLE
Add Bootstrap

### ISSUE THREAD

**Issue by ChicagoDave** [toddlucas/react-tsx-starter#5]
Can you make a branch with Bootstrap 4 beta? Or just show an example of how to add more css files, local or CDN?

**Comment by toddlucas** [comment]
Hi @ChicagoDave, I'll try to get to that. Right now, you can add JS/CSS files to `src/scripts` and `src/styles` and they'll be concatenated into `site.css` and `site.js`. If you want to add a reference to a CDN file, you can add it to `src/views/_appjs.vash` and `src/views/_appcss.vash`. The gulp file would need to be changed to add a non-concatenated file from `scripts` or `styles.

**Comment by toddlucas** [comment]
If you need to add additional CSS files, these are now in the pages directory. I've removed the vash view engine.
